[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Localization color
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "legendary = G.C.RARITY[4],"
position = "after"
payload = "poke_ultrabeast = G.C.RARITY['poke_ultrabeast'],"
match_indent = true